### ISSUE TITLE
Statically link swiftly using Musl on Linux

### ISSUE THREAD

**Issue by cmcgee1024** [swiftlang/swiftly#130] opened 2024-06-22 01:49 UTC
Musl is ideal for permitting Linux binaries to work on a variety of different versions of the Linux kernel and glibc. If swiftly adopted this then it might be less error prone figuring out what supported Linux distribution has the lowest glibc version.

https://www.swift.org/documentation/articles/static-linux-getting-started.html

**Comment by adam-fowler** [comment] 2024-06-22 08:24
This is a duplicate of #119

**Closed** 2024-06-22 08:24 UTC
